# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fileserver.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fileserver.proto',
  package='fileserver',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x66ileserver.proto\x12\nfileserver\"\x1b\n\x0bRequestPath\x12\x0c\n\x04path\x18\x01 \x01(\t\"3\n\x0cResponseFile\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x10\n\x08\x63ontents\x18\x02 \x01(\t2\x91\x01\n\nFileServer\x12>\n\x07GetFile\x12\x17.fileserver.RequestPath\x1a\x18.fileserver.ResponseFile\"\x00\x12\x43\n\nStreamFile\x12\x17.fileserver.RequestPath\x1a\x18.fileserver.ResponseFile\"\x00\x30\x01\x62\x06proto3')
)




_REQUESTPATH = _descriptor.Descriptor(
  name='RequestPath',
  full_name='fileserver.RequestPath',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='fileserver.RequestPath.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=59,
)


_RESPONSEFILE = _descriptor.Descriptor(
  name='ResponseFile',
  full_name='fileserver.ResponseFile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_path', full_name='fileserver.ResponseFile.file_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='contents', full_name='fileserver.ResponseFile.contents', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=112,
)

DESCRIPTOR.message_types_by_name['RequestPath'] = _REQUESTPATH
DESCRIPTOR.message_types_by_name['ResponseFile'] = _RESPONSEFILE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestPath = _reflection.GeneratedProtocolMessageType('RequestPath', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTPATH,
  __module__ = 'fileserver_pb2'
  # @@protoc_insertion_point(class_scope:fileserver.RequestPath)
  ))
_sym_db.RegisterMessage(RequestPath)

ResponseFile = _reflection.GeneratedProtocolMessageType('ResponseFile', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEFILE,
  __module__ = 'fileserver_pb2'
  # @@protoc_insertion_point(class_scope:fileserver.ResponseFile)
  ))
_sym_db.RegisterMessage(ResponseFile)



_FILESERVER = _descriptor.ServiceDescriptor(
  name='FileServer',
  full_name='fileserver.FileServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=115,
  serialized_end=260,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetFile',
    full_name='fileserver.FileServer.GetFile',
    index=0,
    containing_service=None,
    input_type=_REQUESTPATH,
    output_type=_RESPONSEFILE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StreamFile',
    full_name='fileserver.FileServer.StreamFile',
    index=1,
    containing_service=None,
    input_type=_REQUESTPATH,
    output_type=_RESPONSEFILE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FILESERVER)

DESCRIPTOR.services_by_name['FileServer'] = _FILESERVER

# @@protoc_insertion_point(module_scope)
