# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import fileserver_pb2 as fileserver__pb2


class FileServerStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetFile = channel.unary_unary(
        '/fileserver.FileServer/GetFile',
        request_serializer=fileserver__pb2.RequestPath.SerializeToString,
        response_deserializer=fileserver__pb2.ResponseFile.FromString,
        )
    self.StreamFile = channel.unary_stream(
        '/fileserver.FileServer/StreamFile',
        request_serializer=fileserver__pb2.RequestPath.SerializeToString,
        response_deserializer=fileserver__pb2.ResponseFile.FromString,
        )


class FileServerServicer(object):
  """The greeting service definition.
  """

  def GetFile(self, request, context):
    """Returns the entire contents of the file
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StreamFile(self, request, context):
    """Streams the file line by line
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FileServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetFile': grpc.unary_unary_rpc_method_handler(
          servicer.GetFile,
          request_deserializer=fileserver__pb2.RequestPath.FromString,
          response_serializer=fileserver__pb2.ResponseFile.SerializeToString,
      ),
      'StreamFile': grpc.unary_stream_rpc_method_handler(
          servicer.StreamFile,
          request_deserializer=fileserver__pb2.RequestPath.FromString,
          response_serializer=fileserver__pb2.ResponseFile.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'fileserver.FileServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
